[Fix] Password validation
wireapp/wire-ios-utilities pull request #104
Opened 2021-01-18 14:22 UTC by KaterinaWire

## What's new in this PR?

### Issues

During password validation, we separately received validation error that password is `tooShort`, or a list of other password mismatches (e.g. uppercase, lowercase, digits). This is an issue in UI project, because we can update the` Create password ` screen with information that password satisfies minimum length or other requirements.

**E.g.** User A is entering the part of the password: `Qwe1`

**Expectation**
To see that this part satisfies 3 rules: uppercase, lowercase and digits.

**Outcome**
 The password does not satisfy any requirements, because it's less than the minimum number of characters (error = `tooShort`).

### Solutions

Remove unnecessary password length checking from `validatePassword (_ password: String)`.

## Notes

To avoid breaking changes (changing the return type of `validatePassword (_ password: String)`), I added an extra case to the `PasswordCharacterClass` enum. But the name of this enum doesn't sound a right place for checking the password length.

2021-01-20 07:20 UTC, johnxnguyen requested changes
As discussed, I would like to try an alternative approach where we adjust the structure of `PasswordValidationResult` to be able to contain a variety of rule violations. For instance:

```swift
public enum PasswordValidationResult: Equatable {

    /// The password is valid.
    case valid

	/// The password is invalid due to the violations.
	case invalid(violations: [Violation])

	public enum Violation {

	    /// The password is too short.
	    case tooShort
	
	    /// The password is too long.
	    case tooLong
	
	    /// The password contains a disallowed character.
	    case disallowedCharacter(Unicode.Scalar)
	
	    /// The password does not satisfy a requirement for a character class.
	    case missingRequiredClasses(Set<PasswordCharacterClass>)
	}

}
```

2021-01-21 14:59 UTC, johnxnguyen approved these changes

2021-01-21 15:00 UTC, johnxnguyen commented
@KaterinaWire please also update this PR title and description.

2021-01-22 06:43 UTC, typfel approved these changes

2021-01-22 13:44 UTC, KaterinaWire commented
@zenkins release major

2021-01-22 13:45 UTC, merged